check updates from ens-normalize.js
namehash/ens-normalize-python pull request #57
Opened 2023-12-14 10:44 UTC by djstrong

2023-12-15 00:29 UTC, Carbon225 requested changes

2023-12-15 00:29 UTC, Carbon225 commented on tools/updater/package.json
>      "@adraffy/ens-normalize": "github:adraffy/ens-normalize.js#52ce1a2fb22b86416f23a481c956bc74368c35a7"
This hash has to be updated every time.

2023-12-15 08:46 UTC, djstrong commented on tools/updater/package.json
>      "@adraffy/ens-normalize": "github:adraffy/ens-normalize.js#52ce1a2fb22b86416f23a481c956bc74368c35a7"
So we need version without hash?

2023-12-17 02:05 UTC, Carbon225 approved these changes

2023-12-17 10:01 UTC, merged